import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#101415",
        "surface-dim": "#101415",
        "surface-bright": "#363a3b",
        "surface-container-lowest": "#0b0f10",
        "surface-container-low": "#191c1e",
        "surface-container": "#1d2022",
        "surface-container-high": "#272a2c",
        "surface-container-highest": "#323537",
        "surface-variant": "#323537",
        "surface-tint": "#adc6ff",
        "on-surface": "#e0e3e5",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#e0e3e5",
        "inverse-on-surface": "#2d3133",
        outline: "#8c909f",
        "outline-variant": "#424754",
        primary: "#adc6ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#005ac2",
        secondary: "#c2c6db",
        "on-secondary": "#2b3040",
        "secondary-container": "#414658",
        "on-secondary-container": "#b0b4c9",
        "secondary-fixed": "#dee1f7",
        "secondary-fixed-dim": "#c2c6db",
        "on-secondary-fixed": "#161b2b",
        "on-secondary-fixed-variant": "#414658",
        tertiary: "#bcc7de",
        "on-tertiary": "#263143",
        "tertiary-container": "#8691a7",
        "on-tertiary-container": "#1f2a3c",
        "tertiary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#bcc7de",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#3c475a",
        background: "#101415",
        "on-background": "#e0e3e5",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      spacing: {
        base: "4px",
        xs: "0.5rem",
        sm: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        gutter: "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      fontFamily: {
        h1: ["var(--font-manrope)", "sans-serif"],
        h2: ["var(--font-manrope)", "sans-serif"],
        h3: ["var(--font-manrope)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
        "data-mono": ["var(--font-space-grotesk)", "monospace"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "1", letterSpacing: "0", fontWeight: "500" }]
      },
      boxShadow: {
        "electric-glow": "0px 0px 15px rgba(59, 130, 246, 0.4)",
      },
      backgroundImage: {
        "omni-hero": "radial-gradient(circle at 50% -20%, rgba(59,130,246,0.18), transparent 70%)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        glow: {
          "0%, 100%": { opacity: "0.55" },
          "50%": { opacity: "0.85" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        glow: "glow 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
